"""Evaluate the saved Telco churn model pipeline from the command line."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

import joblib
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

from src.data.load_data import clean_telco_data, load_raw_data, split_features_target
from src.features.preprocessing import build_dummy_pipeline
from src.utils.paths import MODEL_ARTIFACT_PATH, PROJECT_ROOT, RAW_DATA_PATH, REPORTS_DIR

RANDOM_STATE = 42
TEST_SIZE = 0.2
EVALUATION_SUMMARY_PATH = REPORTS_DIR / "evaluation_summary.md"
REPORT_DATASET_PATH = RAW_DATA_PATH.relative_to(PROJECT_ROOT).as_posix()
REPORT_MODEL_ARTIFACT_PATH = MODEL_ARTIFACT_PATH.relative_to(PROJECT_ROOT).as_posix()


def evaluate_classifier(model: Pipeline, X_test: pd.DataFrame, y_test: pd.Series) -> dict[str, Any]:
    """Evaluate a fitted classifier on the held-out churn test set."""
    y_pred = model.predict(X_test)

    roc_auc = None
    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)[:, 1]
        roc_auc = roc_auc_score(y_test, y_proba)

    return {
        "roc_auc": None if roc_auc is None else round(float(roc_auc), 4),
        "accuracy": round(float(accuracy_score(y_test, y_pred)), 4),
        "precision": round(float(precision_score(y_test, y_pred, zero_division=0)), 4),
        "recall": round(float(recall_score(y_test, y_pred, zero_division=0)), 4),
        "f1": round(float(f1_score(y_test, y_pred, zero_division=0)), 4),
        "confusion_matrix": confusion_matrix(y_test, y_pred, labels=[0, 1]).tolist(),
    }


def metrics_markdown_table(metrics: dict[str, dict[str, Any]]) -> str:
    """Render model metrics as a compact Markdown table."""
    columns = ["roc_auc", "accuracy", "precision", "recall", "f1"]
    lines = [
        "| model | " + " | ".join(columns) + " |",
        "|---|" + "---|" * len(columns),
    ]
    for model_name, model_metrics in metrics.items():
        values = [str(model_metrics[column]) for column in columns]
        lines.append(f"| {model_name} | " + " | ".join(values) + " |")
    return "\n".join(lines)


def format_metrics_line(model_name: str, metrics: dict[str, Any]) -> str:
    """Format a compact one-line metrics summary for console output."""
    return (
        f"{model_name}: "
        f"roc_auc={metrics['roc_auc']}, "
        f"accuracy={metrics['accuracy']}, "
        f"precision={metrics['precision']}, "
        f"recall={metrics['recall']}, "
        f"f1={metrics['f1']}"
    )


def write_evaluation_summary(
    raw_df: pd.DataFrame,
    X: pd.DataFrame,
    y_train: pd.Series,
    y_test: pd.Series,
    metrics: dict[str, dict[str, Any]],
) -> None:
    """Write a readable Markdown evaluation summary."""
    target_distribution_lines = "\n".join(
        f"- {label}: {count}"
        for label, count in raw_df["Churn"].value_counts().sort_index().items()
    )
    confusion_matrix_lines = "\n".join(
        f"- {model_name}: {model_metrics['confusion_matrix']}"
        for model_name, model_metrics in metrics.items()
    )

    summary = f"""# Evaluation Summary

## Purpose

This report evaluates the saved LogisticRegression preprocessing and model pipeline on the fixed held-out Telco churn split. A DummyClassifier sanity baseline is trained on the same split for comparison.

## Dataset

- Dataset path: `{REPORT_DATASET_PATH}`
- Rows: {raw_df.shape[0]}
- Columns: {raw_df.shape[1]}
- Features: {X.shape[1]}
- Train size: {len(y_train)}
- Test size: {len(y_test)}

## Target Distribution

{target_distribution_lines}

## Model Artifact

- Loaded artifact: `{REPORT_MODEL_ARTIFACT_PATH}`

## Metrics

{metrics_markdown_table(metrics)}

## Confusion Matrices

{confusion_matrix_lines}

## Interpretation

The DummyClassifier is a sanity-check baseline. The LogisticRegression result comes from the saved full scikit-learn preprocessing and model pipeline generated by `python -m src.models.train`.

## Limitations

This evaluation is local and uses a fixed held-out split from a small public dataset. It does not demonstrate production deployment, live monitoring, business impact, API latency, CI reliability or real-world customer impact.

## Run Metadata

- Run date: {datetime.now(timezone.utc).isoformat()}
"""

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    EVALUATION_SUMMARY_PATH.write_text(summary, encoding="utf-8")


def main() -> None:
    """Evaluate the saved LogisticRegression pipeline artifact."""
    if not MODEL_ARTIFACT_PATH.exists():
        raise FileNotFoundError(
            f"Expected model artifact at {MODEL_ARTIFACT_PATH}. "
            "Run `python -m src.models.train` first."
        )

    raw_df = load_raw_data()
    cleaned_df = clean_telco_data(raw_df)
    X, y = split_features_target(cleaned_df)

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=y,
    )

    dummy_pipeline = build_dummy_pipeline(X_train)
    dummy_pipeline.fit(X_train, y_train)
    logistic_pipeline = joblib.load(MODEL_ARTIFACT_PATH)

    metrics = {
        "DummyClassifier": evaluate_classifier(dummy_pipeline, X_test, y_test),
        "LogisticRegression": evaluate_classifier(logistic_pipeline, X_test, y_test),
    }

    write_evaluation_summary(raw_df, X, y_train, y_test, metrics)

    print("Evaluation completed")
    print(f"Dataset: {RAW_DATA_PATH}")
    print(f"Loaded model pipeline artifact from {MODEL_ARTIFACT_PATH}")
    for model_name, model_metrics in metrics.items():
        print(format_metrics_line(model_name, model_metrics))
    print(f"Saved evaluation summary to {EVALUATION_SUMMARY_PATH}")


if __name__ == "__main__":
    main()
